# Generated by Django 5.2 on 2025-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customusermodel_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("teacher", "Teacher"), ("student", "Student")],
                max_length=10,
            ),
        ),
    ]
