# Generated by Django 5.2 on 2025-05-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_class_alter_customusermodel_role_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
