# Generated by Django 5.2 on 2025-05-20 17:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_lesson_class_name_delete_class_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
    ]
