# Generated by Django 5.2 on 2025-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customusermodel_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
