# Generated by Django 5.2 on 2025-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0004_remove_class_teachers"),
        ("users", "0007_customusermodel_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="classes",
            field=models.ManyToManyField(to="app_main.class"),
        ),
    ]
