# Generated by Django 5.2 on 2025-05-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0002_alter_homework_file"),
        ("users", "0007_customusermodel_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="teachers",
            field=models.ManyToManyField(to="users.teacher"),
        ),
    ]
