# Generated by Django 5.2 on 2025-05-22 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0003_class_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="teachers",
        ),
    ]
