# Generated by Django 5.2 on 2025-06-17 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_main", "0005_class_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
